import { describe, it, expect } from 'vitest';
import { chromium } from 'playwright';
import express from 'express';
import { resolve } from 'path';
import { mkdirSync } from 'fs';
import { randomUUID } from 'crypto';
import { portalDatabase } from '../helpers/portal-db';
import { PortalStore } from '../../src/portal/PortalStore';
import { PortalAuth, hashPassword } from '../../src/portal/PortalAuth';
import { PortalBudget } from '../../src/portal/PortalBudget';
import { PortalDocuments } from '../../src/portal/PortalDocuments';
import { PortalConnections } from '../../src/portal/PortalConnections';
import { createPortalRouter } from '../../src/portal/PortalRouter';
import { validatePlan } from '../../src/portal/validation';

describe('portal browser flow',()=>{
  it('completes client signup, editing, admin publication and WhatsApp callback through the UI',async()=>{
    const database=await portalDatabase(),store=new PortalStore(database.db),budget=new PortalBudget(store);
    const app=express();app.use(express.json());
    const server=app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));
    const origin='http://127.0.0.1:'+(server.address() as any).port;
    const auth=new PortalAuth(store,{publicUrl:origin,developmentLinks:true});
    const docs=new PortalDocuments(store,budget,{} as any,{} as any);
    const connections=new PortalConnections(store,{whatsAppOnboardingService:{generateSignupState:()=>randomUUID(),processEmbeddedSignupCallback:async(p:any)=>{
      const id=randomUUID();await store.db.$executeRaw`INSERT INTO "ChannelConnection"(id,"tenantId","accountId",provider,"connectionKey",status,"updatedAt") VALUES (${id},${p.tenantId},${p.accountId},'META_CLOUD',${randomUUID()},'CONNECTED',NOW())`;
      await store.db.$executeRaw`INSERT INTO "WhatsAppBusinessNumber"(id,"tenantId","accountId","phoneNumberId","connectionId",status,"updatedAt") VALUES (${randomUUID()},${p.tenantId},${p.accountId},${p.phoneNumberId},${id},'CONNECTED',NOW())`;
      return {success:true};}},qrSessionManager:{isEnabled:()=>false}} as any);
    app.use('/api',createPortalRouter({store,auth,documents:docs,connections},{conversationEngine:{handleMessage:async()=> 'Salam, livraison f 48 sa3a.'}} as any));
    app.use('/portal-assets',express.static(resolve('src/portal/ui')));
    app.use((_req,res)=>{res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self' https://connect.facebook.net; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://www.facebook.com https://graph.facebook.com; frame-src https://www.facebook.com; base-uri 'none'; form-action 'self'");res.sendFile(resolve('src/portal/ui/index.html'));});
    const adminId=randomUUID(),password='Browser-test-password-2026!';
    await store.db.$executeRaw`INSERT INTO "PortalUser"(id,email,name,"passwordHash",role,"verifiedAt") VALUES (${adminId},'browser-admin@portal.test','Relayqo Admin',${await hashPassword(password)},'ADMIN',NOW())`;
    await store.savePlan(adminId,validatePlan({name:'Commerce Demo',price:299,published:true,modules:['commerce','services','knowledge'],limits:{monthlyUsd:2}}));
    const oldApp=process.env.META_APP_ID,oldConfig=process.env.META_CONFIG_ID;
    process.env.META_APP_ID='browser-test-app';process.env.META_CONFIG_ID='browser-test-config';
    let browser;
    try{
      browser=await chromium.launch({headless:true});
      const clientContext=await browser.newContext({viewport:{width:1440,height:1000}}),adminContext=await browser.newContext({viewport:{width:1440,height:1000}});
      const page=await clientContext.newPage(),ap=await adminContext.newPage(),errors:string[]=[];
      page.on('pageerror',e=>errors.push(e.message));ap.on('pageerror',e=>errors.push(e.message));
      await page.goto(origin+'/signup');await page.locator('.language-select').selectOption('ar');await page.getByLabel('اسمك').waitFor();
      await page.locator('.language-select').selectOption('fr');await page.getByLabel('Votre nom').waitFor();
      await page.locator('.language-select').selectOption('en');await page.getByLabel('Your name').fill('Atlas Boutique');await page.getByLabel('Choose a plan').selectOption({label:'Commerce Demo'});
      await page.getByLabel('Email address').fill('browser-client@portal.test');await page.getByLabel('Password',{exact:true}).fill(password);
      await page.getByRole('button',{name:'Show password'}).click();expect(await page.locator('#password').getAttribute('type')).toBe('text');
      await page.getByRole('button',{name:'Hide password'}).click();expect(await page.locator('#password').getAttribute('type')).toBe('password');
      await page.getByRole('button',{name:'Create account',exact:true}).click();
      await page.getByRole('link',{name:'Open development email link'}).click();await page.getByRole('button',{name:'Confirm',exact:true}).click();
      await page.getByLabel('Email address').fill('browser-client@portal.test');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Log in',exact:true}).click();
      await page.getByRole('heading',{name:/Atlas/}).waitFor();expect(await page.locator('.nav').innerText()).not.toContain('Clients');
      expect(await page.locator('.dashboard-metric').count()).toBe(4);
      expect(await page.getByRole('heading',{name:'Monthly allowance'}).count()).toBe(0);
      await page.getByRole('heading',{name:'Launch checklist'}).waitFor();await page.getByRole('heading',{name:'Message activity'}).waitFor();
      mkdirSync(resolve('output/portal-verification'),{recursive:true});await page.screenshot({path:resolve('output/portal-verification/client-setup-dashboard.png'),fullPage:true});
      await page.locator('.language-select').selectOption('fr');await page.getByRole('link',{name:'Données de l’entreprise'}).waitFor();
      await page.getByRole('link',{name:'Offres',exact:true}).click();await page.getByRole('heading',{name:'Choisir une offre'}).waitFor();
      expect(await page.locator('.plan-grid').innerText()).not.toContain('messages');
      expect(await page.locator('.language-select').inputValue()).toBe('fr');
      await page.locator('.language-select').selectOption('en');
      await page.getByRole('link',{name:'Business data',exact:true}).click();await page.getByLabel('What does your business offer?').fill('Chaussures et vêtements au Maroc');
      await page.getByRole('tab',{name:'Products',exact:true}).click();await page.getByRole('button',{name:'Add product',exact:true}).click();await page.getByLabel('SKU',{exact:true}).fill('SHOE-01');await page.getByLabel('Product name').fill('Babouches artisanales');await page.getByLabel('Price',{exact:true}).first().fill('199.5');
      await page.getByRole('button',{name:'Add variant'}).click();await page.getByLabel('Variant SKU').fill('SHOE-42');await page.getByLabel('Size',{exact:true}).fill('42');await page.getByLabel('Color').fill('Noir');
      await page.getByRole('tab',{name:'FAQs',exact:true}).click();await page.getByRole('button',{name:'Add FAQ',exact:true}).click();await page.getByLabel('Question',{exact:true}).fill('ch7al livraison?');await page.getByLabel('Answer',{exact:true}).fill('Livraison f 48 sa3a.');await page.getByLabel('Language: en, fr, ar or darija').fill('darija');
      await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByText('All changes saved',{exact:true}).waitFor();
      await page.reload();await page.getByRole('tab',{name:'Products',exact:true}).click();await page.getByLabel('Product name').waitFor();expect(await page.getByLabel('Product name').inputValue()).toBe('Babouches artisanales');expect(await page.getByLabel('Variant SKU').inputValue()).toBe('SHOE-42');await page.getByRole('tab',{name:'Profile',exact:true}).click();expect(await page.getByLabel('What does your business offer?').inputValue()).toContain('Maroc');
      await page.getByRole('button',{name:'Send for review'}).click();await page.getByRole('heading',{name:/Atlas/}).waitFor();
      await ap.goto(origin+'/login');await ap.getByLabel('Email address').fill('browser-admin@portal.test');await ap.getByLabel('Password',{exact:true}).fill(password);await ap.getByRole('button',{name:'Log in',exact:true}).click();
      await ap.getByRole('heading',{name:'Platform dashboard'}).waitFor();expect(await ap.locator('.admin-metric').count()).toBe(8);
      await ap.getByRole('heading',{name:'Needs attention'}).waitFor();await ap.screenshot({path:resolve('output/portal-verification/admin-dashboard.png'),fullPage:true});
      await ap.setViewportSize({width:390,height:844});expect(await ap.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
      await ap.screenshot({path:resolve('output/portal-verification/admin-dashboard-mobile.png'),fullPage:true});await ap.setViewportSize({width:1440,height:1000});
      await ap.getByRole('link',{name:'Clients',exact:true}).click();await ap.getByRole('link',{name:'Open ›',exact:true}).click();
      await ap.locator('#aplan').selectOption({label:'Commerce Demo'});await ap.getByRole('tab',{name:'Chatbot & limits',exact:true}).click();await ap.locator('#control-behavior-allowHumanHandoff').check();await ap.getByRole('button',{name:'Save controls'}).click();await ap.getByText('Admin controls saved.',{exact:true}).waitFor();
      expect(await ap.locator('#control-behavior-allowHumanHandoff').isChecked()).toBe(true);
      await ap.locator('#account-unlimited-messages').check();await ap.getByRole('button',{name:'Save controls'}).click();await ap.getByText('Admin controls saved.',{exact:true}).waitFor();
      expect(await ap.locator('#account-unlimited-messages').isChecked()).toBe(true);
      await ap.getByRole('button',{name:'Publish data',exact:true}).click();await ap.getByText('Business data published.',{exact:true}).waitFor();
      await page.addInitScript(()=>{(window as any).FB={init(){},login(callback:any){callback({authResponse:{code:'mock-browser-oauth'}});window.dispatchEvent(new MessageEvent('message',{origin:'https://www.facebook.com',data:JSON.stringify({type:'WA_EMBEDDED_SIGNUP',event:'FINISH',data:{waba_id:'browser-waba',phone_number_id:'browser-phone'}})}));}};});
      await page.goto(origin+'/app/whatsapp');await page.getByRole('button',{name:'Connect with Meta'}).click();await page.getByRole('button',{name:'Continue to WhatsApp'}).click();await page.getByText('CONNECTED',{exact:true}).waitFor();
      await ap.reload();await ap.getByRole('tab',{name:'Overview',exact:true}).click();await ap.locator('#astatus').selectOption('ACTIVE');await ap.getByRole('button',{name:'Save controls'}).click();await ap.getByText('Admin controls saved.',{exact:true}).waitFor();
      await ap.getByRole('tab',{name:'Conversations',exact:true}).click();await ap.locator('#preview-message').fill('ch7al livraison?');await ap.getByRole('button',{name:'Send test'}).click();await ap.getByText('Salam, livraison f 48 sa3a.',{exact:true}).waitFor();
      const user=await store.userByEmail('browser-client@portal.test'),membership=(await store.memberships(user!.id))[0],profile=await store.profile(membership.accountId);
      expect(profile.status).toBe('ACTIVE');expect(profile.published!.products[0].variants[0].sku).toBe('SHOE-42');expect(profile.published!.faqs[0].language).toBe('darija');
      mkdirSync(resolve('output/portal-verification'),{recursive:true});await ap.screenshot({path:resolve('output/portal-verification/admin-desktop.png'),fullPage:true});
      await page.goto(origin+'/app');await page.getByRole('heading',{name:/Atlas/}).waitFor();await page.getByText('No customer messages yet.',{exact:false}).waitFor();await page.screenshot({path:resolve('output/portal-verification/client-desktop.png'),fullPage:true});
      await page.locator('.language-select').selectOption('fr');await page.screenshot({path:resolve('output/portal-verification/client-french-desktop.png'),fullPage:true});
      await page.locator('.language-select').selectOption('en');
      await page.setViewportSize({width:390,height:844});await page.screenshot({path:resolve('output/portal-verification/client-mobile.png'),fullPage:true});
      await page.locator('.language-select').selectOption('ar');await page.getByRole('heading',{name:/مرحبًا بعودتك/}).waitFor();
      expect(await page.locator('html').getAttribute('dir')).toBe('rtl');
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
      await page.screenshot({path:resolve('output/portal-verification/client-arabic-mobile.png'),fullPage:true});
      await page.reload();expect(await page.locator('.language-select').inputValue()).toBe('ar');
      expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
      expect(errors).toEqual([]);
    }finally{
      if(oldApp===undefined)delete process.env.META_APP_ID;else process.env.META_APP_ID=oldApp;
      if(oldConfig===undefined)delete process.env.META_CONFIG_ID;else process.env.META_CONFIG_ID=oldConfig;
      await browser?.close();budget.dispose();await new Promise<void>(r=>server.close(()=>r()));await database.pg.close();
    }
  },120000);
});
